# Defines the pool of backend servers Nginx picks between
upstream laravel_backend {
    # Default Nginx behavior with no extra directive IS round robin
    server app1:9000;
    server app2:9000;

    # Optional — uncomment to weight app1 to get more traffic
    # server app1:9000 weight=2;
    # server app2:9000 weight=1;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laravel_backend;         # app = service name, 9000 = fpm port
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
